create extension if not exists "pg_cron" with schema "pg_catalog";

create sequence "public"."tags_id_seq";


  create table "public"."app_user" (
    "id" uuid not null,
    "email" text not null,
    "name" text,
    "role" text not null default 'member'::text,
    "created_at" timestamp without time zone default now(),
    "first_name" text,
    "last_name" text,
    "dob" date,
    "sex" text,
    "contact_number" text,
    "investor_bio" text,
    "submitted_idea" boolean default false
      );


alter table "public"."app_user" enable row level security;


  create table "public"."blogs" (
    "id" uuid not null default gen_random_uuid(),
    "title" text not null,
    "slug" text not null,
    "excerpt" text,
    "blog_image" text,
    "blog_content" jsonb,
    "tags" text[] default '{}'::text[],
    "created_at" timestamp with time zone default now()
      );



  create table "public"."content_report" (
    "id" uuid not null default gen_random_uuid(),
    "reporter_id" uuid not null,
    "idea_id" uuid,
    "discussion_id" uuid,
    "thread_id" uuid,
    "post_id" uuid,
    "reason" text not null,
    "status" text not null default 'pending'::text,
    "created_at" timestamp without time zone default now()
      );



  create table "public"."financial_data" (
    "id" bigint generated by default as identity not null,
    "ticker" text not null,
    "data" jsonb,
    "inserted_at" timestamp with time zone default now()
      );


alter table "public"."financial_data" enable row level security;


  create table "public"."forum" (
    "id" uuid not null default gen_random_uuid(),
    "title" text not null,
    "created_at" timestamp without time zone default now()
      );



  create table "public"."forum_likes" (
    "id" uuid not null default gen_random_uuid(),
    "thread_id" uuid,
    "post_id" uuid,
    "user_id" uuid not null,
    "created_at" timestamp without time zone default now()
      );



  create table "public"."forum_post" (
    "id" uuid not null default gen_random_uuid(),
    "thread_id" uuid not null,
    "user_id" uuid not null,
    "content" text not null,
    "created_at" timestamp without time zone default now()
      );



  create table "public"."forum_thread" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "title" text not null,
    "created_at" timestamp without time zone default now(),
    "forum_id" uuid not null
      );



  create table "public"."historical_ratios" (
    "id" uuid not null default extensions.uuid_generate_v4(),
    "company" text not null,
    "ratios" jsonb,
    "ai_insight" text,
    "updated_at" timestamp without time zone default CURRENT_TIMESTAMP
      );



  create table "public"."idea_bookmarks" (
    "id" uuid not null default gen_random_uuid(),
    "idea_id" uuid not null,
    "user_id" uuid not null,
    "created_at" timestamp without time zone default now()
      );


alter table "public"."idea_bookmarks" enable row level security;


  create table "public"."idea_discussion" (
    "id" uuid not null default gen_random_uuid(),
    "idea_id" uuid not null,
    "user_id" uuid not null,
    "content" text not null,
    "created_at" timestamp without time zone default now()
      );


alter table "public"."idea_discussion" enable row level security;


  create table "public"."idea_likes" (
    "id" uuid not null default gen_random_uuid(),
    "idea_id" uuid not null,
    "user_id" uuid not null,
    "created_at" timestamp without time zone default now()
      );


alter table "public"."idea_likes" enable row level security;


  create table "public"."ideas_submitted" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "data" jsonb not null,
    "stock_details" jsonb,
    "status" text not null default 'pending'::text,
    "created_at" timestamp without time zone default now()
      );


alter table "public"."ideas_submitted" enable row level security;


  create table "public"."investment_idea" (
    "id" uuid not null default gen_random_uuid(),
    "submitted_id" uuid,
    "user_id" uuid not null,
    "data" jsonb not null,
    "stock_details" jsonb,
    "status" text not null default 'active'::text,
    "created_at" timestamp without time zone default now()
      );


alter table "public"."investment_idea" enable row level security;


  create table "public"."tags" (
    "id" integer not null default nextval('public.tags_id_seq'::regclass),
    "name" text not null,
    "slug" text not null
      );



  create table "public"."tickers" (
    "id" uuid not null default gen_random_uuid(),
    "ticker" character varying not null
      );


alter table "public"."tickers" enable row level security;

alter sequence "public"."tags_id_seq" owned by "public"."tags"."id";

CREATE UNIQUE INDEX app_user_email_key ON public.app_user USING btree (email);

CREATE UNIQUE INDEX app_user_pkey ON public.app_user USING btree (id);

CREATE UNIQUE INDEX blogs_pkey ON public.blogs USING btree (id);

CREATE UNIQUE INDEX blogs_slug_key ON public.blogs USING btree (slug);

CREATE UNIQUE INDEX content_report_pkey ON public.content_report USING btree (id);

CREATE UNIQUE INDEX financial_data_pkey ON public.financial_data USING btree (id);

CREATE UNIQUE INDEX financial_data_ticker_key ON public.financial_data USING btree (ticker);

CREATE UNIQUE INDEX forum_likes_pkey ON public.forum_likes USING btree (id);

CREATE UNIQUE INDEX forum_likes_user_id_thread_id_post_id_key ON public.forum_likes USING btree (user_id, thread_id, post_id);

CREATE UNIQUE INDEX forum_pkey ON public.forum USING btree (id);

CREATE UNIQUE INDEX forum_post_pkey ON public.forum_post USING btree (id);

CREATE UNIQUE INDEX forum_thread_pkey ON public.forum_thread USING btree (id);

CREATE UNIQUE INDEX historical_ratios_pkey ON public.historical_ratios USING btree (id);

CREATE UNIQUE INDEX idea_bookmarks_idea_id_user_id_key ON public.idea_bookmarks USING btree (idea_id, user_id);

CREATE UNIQUE INDEX idea_bookmarks_pkey ON public.idea_bookmarks USING btree (id);

CREATE UNIQUE INDEX idea_discussion_pkey ON public.idea_discussion USING btree (id);

CREATE UNIQUE INDEX idea_likes_idea_id_user_id_key ON public.idea_likes USING btree (idea_id, user_id);

CREATE UNIQUE INDEX idea_likes_pkey ON public.idea_likes USING btree (id);

CREATE UNIQUE INDEX ideas_submitted_pkey ON public.ideas_submitted USING btree (id);

CREATE INDEX idx_ticker ON public.tickers USING btree (ticker);

CREATE UNIQUE INDEX investment_idea_pkey ON public.investment_idea USING btree (id);

CREATE UNIQUE INDEX tags_name_key ON public.tags USING btree (name);

CREATE UNIQUE INDEX tags_pkey ON public.tags USING btree (id);

CREATE UNIQUE INDEX tags_slug_key ON public.tags USING btree (slug);

CREATE UNIQUE INDEX tickers_pkey ON public.tickers USING btree (id);

CREATE UNIQUE INDEX tickers_ticker_key ON public.tickers USING btree (ticker);

alter table "public"."app_user" add constraint "app_user_pkey" PRIMARY KEY using index "app_user_pkey";

alter table "public"."blogs" add constraint "blogs_pkey" PRIMARY KEY using index "blogs_pkey";

alter table "public"."content_report" add constraint "content_report_pkey" PRIMARY KEY using index "content_report_pkey";

alter table "public"."financial_data" add constraint "financial_data_pkey" PRIMARY KEY using index "financial_data_pkey";

alter table "public"."forum" add constraint "forum_pkey" PRIMARY KEY using index "forum_pkey";

alter table "public"."forum_likes" add constraint "forum_likes_pkey" PRIMARY KEY using index "forum_likes_pkey";

alter table "public"."forum_post" add constraint "forum_post_pkey" PRIMARY KEY using index "forum_post_pkey";

alter table "public"."forum_thread" add constraint "forum_thread_pkey" PRIMARY KEY using index "forum_thread_pkey";

alter table "public"."historical_ratios" add constraint "historical_ratios_pkey" PRIMARY KEY using index "historical_ratios_pkey";

alter table "public"."idea_bookmarks" add constraint "idea_bookmarks_pkey" PRIMARY KEY using index "idea_bookmarks_pkey";

alter table "public"."idea_discussion" add constraint "idea_discussion_pkey" PRIMARY KEY using index "idea_discussion_pkey";

alter table "public"."idea_likes" add constraint "idea_likes_pkey" PRIMARY KEY using index "idea_likes_pkey";

alter table "public"."ideas_submitted" add constraint "ideas_submitted_pkey" PRIMARY KEY using index "ideas_submitted_pkey";

alter table "public"."investment_idea" add constraint "investment_idea_pkey" PRIMARY KEY using index "investment_idea_pkey";

alter table "public"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "public"."tickers" add constraint "tickers_pkey" PRIMARY KEY using index "tickers_pkey";

alter table "public"."app_user" add constraint "app_user_email_key" UNIQUE using index "app_user_email_key";

alter table "public"."app_user" add constraint "app_user_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."app_user" validate constraint "app_user_id_fkey";

alter table "public"."blogs" add constraint "blogs_slug_key" UNIQUE using index "blogs_slug_key";

alter table "public"."content_report" add constraint "content_report_discussion_id_fkey" FOREIGN KEY (discussion_id) REFERENCES public.idea_discussion(id) ON DELETE CASCADE not valid;

alter table "public"."content_report" validate constraint "content_report_discussion_id_fkey";

alter table "public"."content_report" add constraint "content_report_idea_id_fkey" FOREIGN KEY (idea_id) REFERENCES public.investment_idea(id) ON DELETE CASCADE not valid;

alter table "public"."content_report" validate constraint "content_report_idea_id_fkey";

alter table "public"."content_report" add constraint "content_report_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.forum_post(id) ON DELETE CASCADE not valid;

alter table "public"."content_report" validate constraint "content_report_post_id_fkey";

alter table "public"."content_report" add constraint "content_report_reporter_id_fkey" FOREIGN KEY (reporter_id) REFERENCES public.app_user(id) ON DELETE CASCADE not valid;

alter table "public"."content_report" validate constraint "content_report_reporter_id_fkey";

alter table "public"."content_report" add constraint "content_report_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES public.forum_thread(id) ON DELETE CASCADE not valid;

alter table "public"."content_report" validate constraint "content_report_thread_id_fkey";

alter table "public"."content_report" add constraint "one_content" CHECK (((((((idea_id IS NOT NULL))::integer + ((discussion_id IS NOT NULL))::integer) + ((thread_id IS NOT NULL))::integer) + ((post_id IS NOT NULL))::integer) = 1)) not valid;

alter table "public"."content_report" validate constraint "one_content";

alter table "public"."financial_data" add constraint "financial_data_ticker_key" UNIQUE using index "financial_data_ticker_key";

alter table "public"."forum_likes" add constraint "forum_likes_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.forum_post(id) ON DELETE CASCADE not valid;

alter table "public"."forum_likes" validate constraint "forum_likes_post_id_fkey";

alter table "public"."forum_likes" add constraint "forum_likes_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES public.forum_thread(id) ON DELETE CASCADE not valid;

alter table "public"."forum_likes" validate constraint "forum_likes_thread_id_fkey";

alter table "public"."forum_likes" add constraint "forum_likes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE not valid;

alter table "public"."forum_likes" validate constraint "forum_likes_user_id_fkey";

alter table "public"."forum_likes" add constraint "forum_likes_user_id_thread_id_post_id_key" UNIQUE using index "forum_likes_user_id_thread_id_post_id_key";

alter table "public"."forum_likes" add constraint "one_target" CHECK ((((thread_id IS NOT NULL) AND (post_id IS NULL)) OR ((post_id IS NOT NULL) AND (thread_id IS NULL)))) not valid;

alter table "public"."forum_likes" validate constraint "one_target";

alter table "public"."forum_post" add constraint "forum_post_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES public.forum_thread(id) ON DELETE CASCADE not valid;

alter table "public"."forum_post" validate constraint "forum_post_thread_id_fkey";

alter table "public"."forum_post" add constraint "forum_post_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE not valid;

alter table "public"."forum_post" validate constraint "forum_post_user_id_fkey";

alter table "public"."forum_thread" add constraint "forum_thread_forum_id_fkey" FOREIGN KEY (forum_id) REFERENCES public.forum(id) ON DELETE CASCADE not valid;

alter table "public"."forum_thread" validate constraint "forum_thread_forum_id_fkey";

alter table "public"."forum_thread" add constraint "forum_thread_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE not valid;

alter table "public"."forum_thread" validate constraint "forum_thread_user_id_fkey";

alter table "public"."idea_bookmarks" add constraint "idea_bookmarks_idea_id_fkey" FOREIGN KEY (idea_id) REFERENCES public.investment_idea(id) ON DELETE CASCADE not valid;

alter table "public"."idea_bookmarks" validate constraint "idea_bookmarks_idea_id_fkey";

alter table "public"."idea_bookmarks" add constraint "idea_bookmarks_idea_id_user_id_key" UNIQUE using index "idea_bookmarks_idea_id_user_id_key";

alter table "public"."idea_bookmarks" add constraint "idea_bookmarks_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE not valid;

alter table "public"."idea_bookmarks" validate constraint "idea_bookmarks_user_id_fkey";

alter table "public"."idea_discussion" add constraint "idea_discussion_idea_id_fkey" FOREIGN KEY (idea_id) REFERENCES public.investment_idea(id) ON DELETE CASCADE not valid;

alter table "public"."idea_discussion" validate constraint "idea_discussion_idea_id_fkey";

alter table "public"."idea_discussion" add constraint "idea_discussion_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE not valid;

alter table "public"."idea_discussion" validate constraint "idea_discussion_user_id_fkey";

alter table "public"."idea_likes" add constraint "idea_likes_idea_id_fkey" FOREIGN KEY (idea_id) REFERENCES public.investment_idea(id) ON DELETE CASCADE not valid;

alter table "public"."idea_likes" validate constraint "idea_likes_idea_id_fkey";

alter table "public"."idea_likes" add constraint "idea_likes_idea_id_user_id_key" UNIQUE using index "idea_likes_idea_id_user_id_key";

alter table "public"."idea_likes" add constraint "idea_likes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE not valid;

alter table "public"."idea_likes" validate constraint "idea_likes_user_id_fkey";

alter table "public"."ideas_submitted" add constraint "ideas_submitted_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE not valid;

alter table "public"."ideas_submitted" validate constraint "ideas_submitted_user_id_fkey";

alter table "public"."investment_idea" add constraint "investment_idea_submitted_id_fkey" FOREIGN KEY (submitted_id) REFERENCES public.ideas_submitted(id) ON DELETE SET NULL not valid;

alter table "public"."investment_idea" validate constraint "investment_idea_submitted_id_fkey";

alter table "public"."investment_idea" add constraint "investment_idea_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.app_user(id) ON DELETE CASCADE not valid;

alter table "public"."investment_idea" validate constraint "investment_idea_user_id_fkey";

alter table "public"."tags" add constraint "tags_name_key" UNIQUE using index "tags_name_key";

alter table "public"."tags" add constraint "tags_slug_key" UNIQUE using index "tags_slug_key";

alter table "public"."tickers" add constraint "tickers_ticker_key" UNIQUE using index "tickers_ticker_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_approved_idea()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  -- Only act when status changes to 'approved'
  if new.status = 'approved' and old.status is distinct from 'approved' then
    -- Insert into investment_idea
    insert into public.investment_idea (
      submitted_id,
      user_id,
      data,
      stock_details,
      status,
      created_at
    )
    values (
      new.id,
      new.user_id,
      new.data,
      new.stock_details,
      'accepted',       -- override status
      now()
    );

    -- Delete the row from ideas_submitted
    delete from public.ideas_submitted where id = new.id;

    -- Update app_user.submitted_idea to true for this user
    update public.app_user
    set submitted_idea = true
    where id = new.user_id;

    -- Since we deleted it, return NULL to stop further propagation
    return null;
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.app_user (id, email, name, role, created_at)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'full_name', ''), NEW.email),
    'member',
    NOW()
  );
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_super_admin(user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  SELECT role = 'super_admin' 
  FROM public.app_user 
  WHERE id = user_id;
$function$
;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$
;

grant delete on table "public"."app_user" to "anon";

grant insert on table "public"."app_user" to "anon";

grant references on table "public"."app_user" to "anon";

grant select on table "public"."app_user" to "anon";

grant trigger on table "public"."app_user" to "anon";

grant truncate on table "public"."app_user" to "anon";

grant update on table "public"."app_user" to "anon";

grant delete on table "public"."app_user" to "authenticated";

grant insert on table "public"."app_user" to "authenticated";

grant references on table "public"."app_user" to "authenticated";

grant select on table "public"."app_user" to "authenticated";

grant trigger on table "public"."app_user" to "authenticated";

grant truncate on table "public"."app_user" to "authenticated";

grant update on table "public"."app_user" to "authenticated";

grant delete on table "public"."app_user" to "service_role";

grant insert on table "public"."app_user" to "service_role";

grant references on table "public"."app_user" to "service_role";

grant select on table "public"."app_user" to "service_role";

grant trigger on table "public"."app_user" to "service_role";

grant truncate on table "public"."app_user" to "service_role";

grant update on table "public"."app_user" to "service_role";

grant delete on table "public"."blogs" to "anon";

grant insert on table "public"."blogs" to "anon";

grant references on table "public"."blogs" to "anon";

grant select on table "public"."blogs" to "anon";

grant trigger on table "public"."blogs" to "anon";

grant truncate on table "public"."blogs" to "anon";

grant update on table "public"."blogs" to "anon";

grant delete on table "public"."blogs" to "authenticated";

grant insert on table "public"."blogs" to "authenticated";

grant references on table "public"."blogs" to "authenticated";

grant select on table "public"."blogs" to "authenticated";

grant trigger on table "public"."blogs" to "authenticated";

grant truncate on table "public"."blogs" to "authenticated";

grant update on table "public"."blogs" to "authenticated";

grant delete on table "public"."blogs" to "service_role";

grant insert on table "public"."blogs" to "service_role";

grant references on table "public"."blogs" to "service_role";

grant select on table "public"."blogs" to "service_role";

grant trigger on table "public"."blogs" to "service_role";

grant truncate on table "public"."blogs" to "service_role";

grant update on table "public"."blogs" to "service_role";

grant delete on table "public"."content_report" to "anon";

grant insert on table "public"."content_report" to "anon";

grant references on table "public"."content_report" to "anon";

grant select on table "public"."content_report" to "anon";

grant trigger on table "public"."content_report" to "anon";

grant truncate on table "public"."content_report" to "anon";

grant update on table "public"."content_report" to "anon";

grant delete on table "public"."content_report" to "authenticated";

grant insert on table "public"."content_report" to "authenticated";

grant references on table "public"."content_report" to "authenticated";

grant select on table "public"."content_report" to "authenticated";

grant trigger on table "public"."content_report" to "authenticated";

grant truncate on table "public"."content_report" to "authenticated";

grant update on table "public"."content_report" to "authenticated";

grant delete on table "public"."content_report" to "service_role";

grant insert on table "public"."content_report" to "service_role";

grant references on table "public"."content_report" to "service_role";

grant select on table "public"."content_report" to "service_role";

grant trigger on table "public"."content_report" to "service_role";

grant truncate on table "public"."content_report" to "service_role";

grant update on table "public"."content_report" to "service_role";

grant delete on table "public"."financial_data" to "anon";

grant insert on table "public"."financial_data" to "anon";

grant references on table "public"."financial_data" to "anon";

grant select on table "public"."financial_data" to "anon";

grant trigger on table "public"."financial_data" to "anon";

grant truncate on table "public"."financial_data" to "anon";

grant update on table "public"."financial_data" to "anon";

grant delete on table "public"."financial_data" to "authenticated";

grant insert on table "public"."financial_data" to "authenticated";

grant references on table "public"."financial_data" to "authenticated";

grant select on table "public"."financial_data" to "authenticated";

grant trigger on table "public"."financial_data" to "authenticated";

grant truncate on table "public"."financial_data" to "authenticated";

grant update on table "public"."financial_data" to "authenticated";

grant delete on table "public"."financial_data" to "service_role";

grant insert on table "public"."financial_data" to "service_role";

grant references on table "public"."financial_data" to "service_role";

grant select on table "public"."financial_data" to "service_role";

grant trigger on table "public"."financial_data" to "service_role";

grant truncate on table "public"."financial_data" to "service_role";

grant update on table "public"."financial_data" to "service_role";

grant delete on table "public"."forum" to "anon";

grant insert on table "public"."forum" to "anon";

grant references on table "public"."forum" to "anon";

grant select on table "public"."forum" to "anon";

grant trigger on table "public"."forum" to "anon";

grant truncate on table "public"."forum" to "anon";

grant update on table "public"."forum" to "anon";

grant delete on table "public"."forum" to "authenticated";

grant insert on table "public"."forum" to "authenticated";

grant references on table "public"."forum" to "authenticated";

grant select on table "public"."forum" to "authenticated";

grant trigger on table "public"."forum" to "authenticated";

grant truncate on table "public"."forum" to "authenticated";

grant update on table "public"."forum" to "authenticated";

grant delete on table "public"."forum" to "service_role";

grant insert on table "public"."forum" to "service_role";

grant references on table "public"."forum" to "service_role";

grant select on table "public"."forum" to "service_role";

grant trigger on table "public"."forum" to "service_role";

grant truncate on table "public"."forum" to "service_role";

grant update on table "public"."forum" to "service_role";

grant delete on table "public"."forum_likes" to "anon";

grant insert on table "public"."forum_likes" to "anon";

grant references on table "public"."forum_likes" to "anon";

grant select on table "public"."forum_likes" to "anon";

grant trigger on table "public"."forum_likes" to "anon";

grant truncate on table "public"."forum_likes" to "anon";

grant update on table "public"."forum_likes" to "anon";

grant delete on table "public"."forum_likes" to "authenticated";

grant insert on table "public"."forum_likes" to "authenticated";

grant references on table "public"."forum_likes" to "authenticated";

grant select on table "public"."forum_likes" to "authenticated";

grant trigger on table "public"."forum_likes" to "authenticated";

grant truncate on table "public"."forum_likes" to "authenticated";

grant update on table "public"."forum_likes" to "authenticated";

grant delete on table "public"."forum_likes" to "service_role";

grant insert on table "public"."forum_likes" to "service_role";

grant references on table "public"."forum_likes" to "service_role";

grant select on table "public"."forum_likes" to "service_role";

grant trigger on table "public"."forum_likes" to "service_role";

grant truncate on table "public"."forum_likes" to "service_role";

grant update on table "public"."forum_likes" to "service_role";

grant delete on table "public"."forum_post" to "anon";

grant insert on table "public"."forum_post" to "anon";

grant references on table "public"."forum_post" to "anon";

grant select on table "public"."forum_post" to "anon";

grant trigger on table "public"."forum_post" to "anon";

grant truncate on table "public"."forum_post" to "anon";

grant update on table "public"."forum_post" to "anon";

grant delete on table "public"."forum_post" to "authenticated";

grant insert on table "public"."forum_post" to "authenticated";

grant references on table "public"."forum_post" to "authenticated";

grant select on table "public"."forum_post" to "authenticated";

grant trigger on table "public"."forum_post" to "authenticated";

grant truncate on table "public"."forum_post" to "authenticated";

grant update on table "public"."forum_post" to "authenticated";

grant delete on table "public"."forum_post" to "service_role";

grant insert on table "public"."forum_post" to "service_role";

grant references on table "public"."forum_post" to "service_role";

grant select on table "public"."forum_post" to "service_role";

grant trigger on table "public"."forum_post" to "service_role";

grant truncate on table "public"."forum_post" to "service_role";

grant update on table "public"."forum_post" to "service_role";

grant delete on table "public"."forum_thread" to "anon";

grant insert on table "public"."forum_thread" to "anon";

grant references on table "public"."forum_thread" to "anon";

grant select on table "public"."forum_thread" to "anon";

grant trigger on table "public"."forum_thread" to "anon";

grant truncate on table "public"."forum_thread" to "anon";

grant update on table "public"."forum_thread" to "anon";

grant delete on table "public"."forum_thread" to "authenticated";

grant insert on table "public"."forum_thread" to "authenticated";

grant references on table "public"."forum_thread" to "authenticated";

grant select on table "public"."forum_thread" to "authenticated";

grant trigger on table "public"."forum_thread" to "authenticated";

grant truncate on table "public"."forum_thread" to "authenticated";

grant update on table "public"."forum_thread" to "authenticated";

grant delete on table "public"."forum_thread" to "service_role";

grant insert on table "public"."forum_thread" to "service_role";

grant references on table "public"."forum_thread" to "service_role";

grant select on table "public"."forum_thread" to "service_role";

grant trigger on table "public"."forum_thread" to "service_role";

grant truncate on table "public"."forum_thread" to "service_role";

grant update on table "public"."forum_thread" to "service_role";

grant delete on table "public"."historical_ratios" to "anon";

grant insert on table "public"."historical_ratios" to "anon";

grant references on table "public"."historical_ratios" to "anon";

grant select on table "public"."historical_ratios" to "anon";

grant trigger on table "public"."historical_ratios" to "anon";

grant truncate on table "public"."historical_ratios" to "anon";

grant update on table "public"."historical_ratios" to "anon";

grant delete on table "public"."historical_ratios" to "authenticated";

grant insert on table "public"."historical_ratios" to "authenticated";

grant references on table "public"."historical_ratios" to "authenticated";

grant select on table "public"."historical_ratios" to "authenticated";

grant trigger on table "public"."historical_ratios" to "authenticated";

grant truncate on table "public"."historical_ratios" to "authenticated";

grant update on table "public"."historical_ratios" to "authenticated";

grant delete on table "public"."historical_ratios" to "service_role";

grant insert on table "public"."historical_ratios" to "service_role";

grant references on table "public"."historical_ratios" to "service_role";

grant select on table "public"."historical_ratios" to "service_role";

grant trigger on table "public"."historical_ratios" to "service_role";

grant truncate on table "public"."historical_ratios" to "service_role";

grant update on table "public"."historical_ratios" to "service_role";

grant delete on table "public"."idea_bookmarks" to "anon";

grant insert on table "public"."idea_bookmarks" to "anon";

grant references on table "public"."idea_bookmarks" to "anon";

grant select on table "public"."idea_bookmarks" to "anon";

grant trigger on table "public"."idea_bookmarks" to "anon";

grant truncate on table "public"."idea_bookmarks" to "anon";

grant update on table "public"."idea_bookmarks" to "anon";

grant delete on table "public"."idea_bookmarks" to "authenticated";

grant insert on table "public"."idea_bookmarks" to "authenticated";

grant references on table "public"."idea_bookmarks" to "authenticated";

grant select on table "public"."idea_bookmarks" to "authenticated";

grant trigger on table "public"."idea_bookmarks" to "authenticated";

grant truncate on table "public"."idea_bookmarks" to "authenticated";

grant update on table "public"."idea_bookmarks" to "authenticated";

grant delete on table "public"."idea_bookmarks" to "service_role";

grant insert on table "public"."idea_bookmarks" to "service_role";

grant references on table "public"."idea_bookmarks" to "service_role";

grant select on table "public"."idea_bookmarks" to "service_role";

grant trigger on table "public"."idea_bookmarks" to "service_role";

grant truncate on table "public"."idea_bookmarks" to "service_role";

grant update on table "public"."idea_bookmarks" to "service_role";

grant delete on table "public"."idea_discussion" to "anon";

grant insert on table "public"."idea_discussion" to "anon";

grant references on table "public"."idea_discussion" to "anon";

grant select on table "public"."idea_discussion" to "anon";

grant trigger on table "public"."idea_discussion" to "anon";

grant truncate on table "public"."idea_discussion" to "anon";

grant update on table "public"."idea_discussion" to "anon";

grant delete on table "public"."idea_discussion" to "authenticated";

grant insert on table "public"."idea_discussion" to "authenticated";

grant references on table "public"."idea_discussion" to "authenticated";

grant select on table "public"."idea_discussion" to "authenticated";

grant trigger on table "public"."idea_discussion" to "authenticated";

grant truncate on table "public"."idea_discussion" to "authenticated";

grant update on table "public"."idea_discussion" to "authenticated";

grant delete on table "public"."idea_discussion" to "service_role";

grant insert on table "public"."idea_discussion" to "service_role";

grant references on table "public"."idea_discussion" to "service_role";

grant select on table "public"."idea_discussion" to "service_role";

grant trigger on table "public"."idea_discussion" to "service_role";

grant truncate on table "public"."idea_discussion" to "service_role";

grant update on table "public"."idea_discussion" to "service_role";

grant delete on table "public"."idea_likes" to "anon";

grant insert on table "public"."idea_likes" to "anon";

grant references on table "public"."idea_likes" to "anon";

grant select on table "public"."idea_likes" to "anon";

grant trigger on table "public"."idea_likes" to "anon";

grant truncate on table "public"."idea_likes" to "anon";

grant update on table "public"."idea_likes" to "anon";

grant delete on table "public"."idea_likes" to "authenticated";

grant insert on table "public"."idea_likes" to "authenticated";

grant references on table "public"."idea_likes" to "authenticated";

grant select on table "public"."idea_likes" to "authenticated";

grant trigger on table "public"."idea_likes" to "authenticated";

grant truncate on table "public"."idea_likes" to "authenticated";

grant update on table "public"."idea_likes" to "authenticated";

grant delete on table "public"."idea_likes" to "service_role";

grant insert on table "public"."idea_likes" to "service_role";

grant references on table "public"."idea_likes" to "service_role";

grant select on table "public"."idea_likes" to "service_role";

grant trigger on table "public"."idea_likes" to "service_role";

grant truncate on table "public"."idea_likes" to "service_role";

grant update on table "public"."idea_likes" to "service_role";

grant delete on table "public"."ideas_submitted" to "anon";

grant insert on table "public"."ideas_submitted" to "anon";

grant references on table "public"."ideas_submitted" to "anon";

grant select on table "public"."ideas_submitted" to "anon";

grant trigger on table "public"."ideas_submitted" to "anon";

grant truncate on table "public"."ideas_submitted" to "anon";

grant update on table "public"."ideas_submitted" to "anon";

grant delete on table "public"."ideas_submitted" to "authenticated";

grant insert on table "public"."ideas_submitted" to "authenticated";

grant references on table "public"."ideas_submitted" to "authenticated";

grant select on table "public"."ideas_submitted" to "authenticated";

grant trigger on table "public"."ideas_submitted" to "authenticated";

grant truncate on table "public"."ideas_submitted" to "authenticated";

grant update on table "public"."ideas_submitted" to "authenticated";

grant delete on table "public"."ideas_submitted" to "service_role";

grant insert on table "public"."ideas_submitted" to "service_role";

grant references on table "public"."ideas_submitted" to "service_role";

grant select on table "public"."ideas_submitted" to "service_role";

grant trigger on table "public"."ideas_submitted" to "service_role";

grant truncate on table "public"."ideas_submitted" to "service_role";

grant update on table "public"."ideas_submitted" to "service_role";

grant delete on table "public"."investment_idea" to "anon";

grant insert on table "public"."investment_idea" to "anon";

grant references on table "public"."investment_idea" to "anon";

grant select on table "public"."investment_idea" to "anon";

grant trigger on table "public"."investment_idea" to "anon";

grant truncate on table "public"."investment_idea" to "anon";

grant update on table "public"."investment_idea" to "anon";

grant delete on table "public"."investment_idea" to "authenticated";

grant insert on table "public"."investment_idea" to "authenticated";

grant references on table "public"."investment_idea" to "authenticated";

grant select on table "public"."investment_idea" to "authenticated";

grant trigger on table "public"."investment_idea" to "authenticated";

grant truncate on table "public"."investment_idea" to "authenticated";

grant update on table "public"."investment_idea" to "authenticated";

grant delete on table "public"."investment_idea" to "service_role";

grant insert on table "public"."investment_idea" to "service_role";

grant references on table "public"."investment_idea" to "service_role";

grant select on table "public"."investment_idea" to "service_role";

grant trigger on table "public"."investment_idea" to "service_role";

grant truncate on table "public"."investment_idea" to "service_role";

grant update on table "public"."investment_idea" to "service_role";

grant delete on table "public"."tags" to "anon";

grant insert on table "public"."tags" to "anon";

grant references on table "public"."tags" to "anon";

grant select on table "public"."tags" to "anon";

grant trigger on table "public"."tags" to "anon";

grant truncate on table "public"."tags" to "anon";

grant update on table "public"."tags" to "anon";

grant delete on table "public"."tags" to "authenticated";

grant insert on table "public"."tags" to "authenticated";

grant references on table "public"."tags" to "authenticated";

grant select on table "public"."tags" to "authenticated";

grant trigger on table "public"."tags" to "authenticated";

grant truncate on table "public"."tags" to "authenticated";

grant update on table "public"."tags" to "authenticated";

grant delete on table "public"."tags" to "service_role";

grant insert on table "public"."tags" to "service_role";

grant references on table "public"."tags" to "service_role";

grant select on table "public"."tags" to "service_role";

grant trigger on table "public"."tags" to "service_role";

grant truncate on table "public"."tags" to "service_role";

grant update on table "public"."tags" to "service_role";

grant delete on table "public"."tickers" to "anon";

grant insert on table "public"."tickers" to "anon";

grant references on table "public"."tickers" to "anon";

grant select on table "public"."tickers" to "anon";

grant trigger on table "public"."tickers" to "anon";

grant truncate on table "public"."tickers" to "anon";

grant update on table "public"."tickers" to "anon";

grant delete on table "public"."tickers" to "authenticated";

grant insert on table "public"."tickers" to "authenticated";

grant references on table "public"."tickers" to "authenticated";

grant select on table "public"."tickers" to "authenticated";

grant trigger on table "public"."tickers" to "authenticated";

grant truncate on table "public"."tickers" to "authenticated";

grant update on table "public"."tickers" to "authenticated";

grant delete on table "public"."tickers" to "service_role";

grant insert on table "public"."tickers" to "service_role";

grant references on table "public"."tickers" to "service_role";

grant select on table "public"."tickers" to "service_role";

grant trigger on table "public"."tickers" to "service_role";

grant truncate on table "public"."tickers" to "service_role";

grant update on table "public"."tickers" to "service_role";


  create policy "Enable read access for all users"
  on "public"."app_user"
  as permissive
  for select
  to public
using (true);



  create policy "Super admin app_user"
  on "public"."app_user"
  as permissive
  for all
  to authenticated
using (public.is_super_admin(auth.uid()));



  create policy "Update user detail "
  on "public"."app_user"
  as permissive
  for update
  to authenticated
using (true);



  create policy "read auth bruh"
  on "public"."app_user"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable read access for all users"
  on "public"."blogs"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."financial_data"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."financial_data"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."idea_bookmarks"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Enable read access for all users"
  on "public"."idea_bookmarks"
  as permissive
  for select
  to public
using (true);



  create policy "Enable all for authenticated users only"
  on "public"."idea_discussion"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Enable read access for all users"
  on "public"."idea_discussion"
  as permissive
  for select
  to public
using (true);



  create policy "Enable All for authenticated users only"
  on "public"."idea_likes"
  as permissive
  for all
  to authenticated
using (true);



  create policy "Enable read access for all users"
  on "public"."idea_likes"
  as permissive
  for select
  to public
using (true);



  create policy "Enable Update for authenticated users only"
  on "public"."ideas_submitted"
  as permissive
  for update
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."ideas_submitted"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable users to view their own data only"
  on "public"."ideas_submitted"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Super admins allow all"
  on "public"."ideas_submitted"
  as permissive
  for all
  to authenticated
using (public.is_super_admin(auth.uid()));



  create policy "enable delete"
  on "public"."ideas_submitted"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."investment_idea"
  as permissive
  for select
  to public
using (true);



  create policy "Super admins can Update"
  on "public"."investment_idea"
  as permissive
  for all
  to authenticated
using (public.is_super_admin(auth.uid()));



  create policy "Public can view tags"
  on "public"."tags"
  as permissive
  for select
  to public
using (true);



  create policy "Allow authenticated users to read tickers"
  on "public"."tickers"
  as permissive
  for select
  to authenticated
using (true);


CREATE TRIGGER trigger_approved_idea AFTER UPDATE OF status ON public.ideas_submitted FOR EACH ROW EXECUTE FUNCTION public.handle_approved_idea();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Allow Delete of authenticated users yfngw_0"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using ((bucket_id = 'user-uploads'::text));



  create policy "Allow select yfngw_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'user-uploads'::text));



  create policy "Allow upload of authenticated users yfngw_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'user-uploads'::text));



  create policy "Authenticated Upload"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'blog-images'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Give anon users access to JPG images in folder yfngw_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'user-uploads'::text) AND (storage.extension(name) = 'jpg'::text) AND (lower((storage.foldername(name))[1]) = 'public'::text) AND (auth.role() = 'anon'::text)));



  create policy "Public Access"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'blog-images'::text));



